CREATE DATABASE LAB4;
USE LAB4;
CREATE TABLE CUSTOMER
(
	CustomerId int IDENTITY(1,1) PRIMARY KEY,
	Name varchar(50) NOT NULL,
	Age int NOT NULL CHECK (Age >= 18),
	Address varchar(200) NULL  DEFAULT  'Dhaka',
	Salary decimal(18,2) NULL
)

INSERT INTO CUSTOMER (Name, Age, Address, Salary) 
VALUES ('Rahim', 32, 'Gulshan',2000.35),
       ('Karim', 25, 'Dhanmondi',1500.22),
       ('Hashim', 23, 'Mottijheel',2000.00),
       ('Khan', 25, 'Tejgaon',6500.00),
       ('Rahman', 27, 'Wari',8500.00),
       ('Mehedi', 22, 'Mohammadpur',4500.00),
       ('Kashim', 24, 'Kakrail',10000.00),
       ('Kazi', 22, 'Kakrail',1000.00)
       
       SELECT * FROM CUSTOMER;

--SALARY STARTS WITH 200--
SELECT * FROM CUSTOMER WHERE Salary LIKE '200%';

--NAME STARTS WITH 'KA'--
SELECT * FROM CUSTOMER WHERE Name LIKE 'Ka%';

--2ND DIGIT OF ADDRESS 'H'--
SELECT * FROM CUSTOMER WHERE Address LIKE '_h%';

--CUSTOMER WHOSE AGE IS 23,27,32--
SELECT * FROM CUSTOMER WHERE AGE IN (23, 27,32);

--AGE RANGE: 23-32--
SELECT * FROM CUSTOMER WHERE AGE BETWEEN 23 AND 32;

--WHOSE ADDRESS LAST DIGIT IS 'N' OR FIRST DIGIT IS 'D'--
SELECT * FROM CUSTOMER WHERE Address LIKE '%n' OR Address LIKE 'D%';

--AGE BETWEEN 23-27--
SELECT * FROM CUSTOMER WHERE Age BETWEEN 23 AND 27;

--AGE 24 DONT WANT TO WATCH--
SELECT * FROM CUSTOMER WHERE AGE NOT IN (24);

--50% PEOPLE WANT TO WATCH--
SELECT TOP 50 PERCENT * FROM CUSTOMER;

--AGE SHOW MAXIMUM SALARY GROUP BY AGE--
SELECT Age, MAX(Salary) AS 'MAXIMUM SALARY' FROM CUSTOMER GROUP BY Age;

--CUSTOMER AGE ,MAXIMUM SALARY NAME STARTS WITH 'KA' AND AGE>=25--
SELECT NAME,AGE,MAX(SALARY) AS 'MAXIMUM SALARY' 
FROM CUSTOMER GROUP BY NAME,Age 
HAVING NAME LIKE 'Ka%' AND Age>=25;